version: "3.7"  

services:

  insightface:
    image: insightface
    build:
      context: .
      dockerfile: Dockerfile_CUDA
    volumes:
      - ./httpsrv.py:/usr/src/app/httpsrv.py:ro
    ports:
      - 8000:5000
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
