version: "3.7"  

services:

  insightface:
    image: insightface
    build:
      context: .
      dockerfile: Dockerfile_CUDA
    ports:
      - 5000:5000
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
