FROM nvidia/cuda:11.0-cudnn8-runtime-ubuntu18.04

WORKDIR /usr/src/app

RUN apt-get update && \
apt-get install git wget unzip libglib2.0-0 libgl1-mesa-dev python3 python3-pip -y && \
git clone https://github.com/deepinsight/insightface.git && \
pip3 install --upgrade pip && \
pip3 install --no-cache-dir onnx onnxruntime-gpu flask waitress pypandoc scikit-image opencv-python && \
cd insightface/python-package && python3 setup.py install && \
wget https://github.com/pi-null-mezon/deepmodels/raw/main/antelope.zip && \
mkdir -p ~/.insightface/models && \
unzip -d ~/.insightface/models antelope.zip && \
rm antelope.zip

EXPOSE 5000

ENTRYPOINT ["python3", "./httpsrv.py"]
